Run shfmt

diff --git a/previewers/fzf_preview b/previewers/fzf_preview
--- a/previewers/fzf_preview
+++ b/previewers/fzf_preview
@@ -5,56 +5,56 @@ path="$1"
 
 # Function to get terminal size
 get_terminal_size() {
-  local size
-  size=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
-  if [[ $size = x ]]; then
-    size=$(stty size < /dev/tty || echo "24x80")
-  fi
+	local size
+	size=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
+	if [[ $size = x ]]; then
+		size=$(stty size </dev/tty || echo "24x80")
+	fi
 
-  echo "$size"
+	echo "$size"
 }
 
 # Function to preview a file
 preview_file() {
-  local file_path="$1"
-  if command -v bat > /dev/null 2>&1; then
-    bat --style=numbers --color=always "$file_path"
-  else
-    cat "$file_path"
-  fi
+	local file_path="$1"
+	if command -v bat >/dev/null 2>&1; then
+		bat --style=numbers --color=always "$file_path"
+	else
+		cat "$file_path"
+	fi
 }
 
 # Function to preview an image
 preview_image() {
-  local image_path="$1"
-  if command -v chafa > /dev/null 2>&1; then
-    chafa --size "$(get_terminal_size)" "$image_path"
-  else
-    ls -l "$image_path"
-  fi
+	local image_path="$1"
+	if command -v chafa >/dev/null 2>&1; then
+		chafa --size "$(get_terminal_size)" "$image_path"
+	else
+		ls -l "$image_path"
+	fi
 }
 
 # Check if the path is a directory
 if [[ -d "$path" ]]; then
-  # Use eza for directories, fallback to ls if eza is not installed
-  if command -v eza > /dev/null 2>&1; then
-    eza -l --color=always "$path"
-  else
-    ls -l --color=always "$path"
-  fi
+	# Use eza for directories, fallback to ls if eza is not installed
+	if command -v eza >/dev/null 2>&1; then
+		eza -l --color=always "$path"
+	else
+		ls -l --color=always "$path"
+	fi
 elif [[ -f "$path" ]]; then
-  # Check if the file command is available
-  if command -v file > /dev/null 2>&1; then
-    # Check if the file is an image
-    if file --mime-type "$path" | grep -q 'image/'; then
-      preview_image "$path"
-    else
-      preview_file "$path"
-    fi
-  else
-    # Default to bat if file command is not available
-    preview_file "$path"
-  fi
+	# Check if the file command is available
+	if command -v file >/dev/null 2>&1; then
+		# Check if the file is an image
+		if file --mime-type "$path" | grep -q 'image/'; then
+			preview_image "$path"
+		else
+			preview_file "$path"
+		fi
+	else
+		# Default to bat if file command is not available
+		preview_file "$path"
+	fi
 else
-  echo "Invalid path"
+	echo "Invalid path"
 fi
